services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 4001:4001
    volumes:
      - .:/usr/src/app
  test:
    build:
      context: .
      dockerfile: /test/Dockerfile.test
    command: npm test
    volumes: 
      - .:/usr/src/test/app
    # depends_on:
    #   - server