services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 4001:4001

  test:
    build:
      context: .
      dockerfile: /test/Dockerfile.test
    command: sh -c "while ! nc -z server 4001; do sleep 1; done && npm test"
    ports:
      - 4000:4000
    depends_on:
      - server
    